[package]
name = "rust-http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
firebase-rs = "2.1.1"
tokio = { version = "1.37.0", features = ["full"] }
serde = "1.0.198"
serde_json = "1.0.116"
